# Site settings
title: Amutay
email: 
description: > Grupo 13
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username: Grupo13UPCH

# Build settings
markdown: kramdown
